FROM golang:1.25.4-alpine3.22 AS builder-stage

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /donela ./cmd/app

FROM debian:bookworm-slim

WORKDIR /

COPY --from=builder-stage /donela /donela
COPY --from=builder-stage /app/.env .

ENTRYPOINT ["/donela"]